name: Update Docs
on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  update_docs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Build Docs
        run: cargo doc -j$(nproc) --release --verbose --no-deps
      - name: Add base index file
        run: |
          echo "<meta http-equiv=\"refresh\" content=\"0; url=soap_rs\">" > target/doc/index.html
      - name: Clean
        run: |
          find . | grep -vw 'target\|.git\|.cargo\|.gitignore' | xargs rm -rf; echo
      - name: Commit
        uses: test-room-7/action-update-file@v1
        with:
            file-path: target/doc/**/*
            commit-msg: 'ci(docs): update docs'
            branch: docs
            allow-dot: true
            allow-removing: true
            github-token: ${{ secrets.GITHUB_TOKEN }}
